outputs:
  donald:
    directory: ./test
    uri: "https://example.com"
shows:
  - title: Show Name
    summary: A summary of the show
    author: Station name
    url: https://example.com/stream
    duration: 5
    days:
      - monday
      - tuesday
      - wednesday
      - thursday
      - friday
    time: 07:00
    output: donald
